// Generated by CoffeeScript 1.12.5
var html2js, pug;

pug = require('pug');

html2js = require('html2js');

module.exports = function(source, other) {
  var e, html, newSource, options, ref, reg, tmpWrap;
  this.cacheable();
  try {
    reg = new RegExp('^<([^>\s]+)[^>]*>(.*?<\/\\1>)?$');
    if (!reg.test(source)) {
      html = pug.render(source, {});
      options = {
        mode: 'compress',
        wrap: false
      };
    } else {
      html = source;
    }
    newSource = html2js(html, options);
    tmpWrap = ((ref = this.query) != null ? ref.wrap : void 0) || null;
    if ('commonjs' === tmpWrap) {
      newSource = 'var tpl = ' + newSource + ';\n module.exports = tpl;';
    } else {
      newSource = 'const tpl = `' + newSource + '`;export default tpl;';
    }
  } catch (error) {
    e = error;
    this.callback(e, '', other);
  }
  this.callback(null, newSource, other);
};
